### ISSUE TITLE
What is `pip install -e .` about?

### ISSUE THREAD

**Issue by wanzhouliu** [GaTech-RL2/nvf_cvpr24#1]
Thank you for your marvelous work! I tried to deploy this project, but when I `cd` into it and run `pip install -e .`, I got the following error:

```
Obtaining file:///nvf_cvpr24
ERROR: file:///nvf_cvpr24 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

And these two files did really not exist in the repo. Is there something wrong with that? Thanks again!

**Comment by jianchaoci** [comment]
> Thank you for your marvelous work! I tried to deploy this project, but when I `cd` into it and run `pip install -e .`, I got the following error:
> 
> ```
> Obtaining file:///nvf_cvpr24
> ERROR: file:///nvf_cvpr24 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
> ```
> 
> And these two files did really not exist in the repo. Is there something wrong with that? Thanks again!
I get the same problem, have you solve this problem?

**Comment by wanzhouliu** [comment]
> > I get the same problem, have you solve this problem?

Not yet, hope they may find this issue soon. :)

**Comment by JesseDill** [comment]
The pyproject.toml contains all the dependencies for nerfstudio. When porting our code base from our dev repo, we forgot to add the pyproject.toml file. It's been pushed to the main branch now, sorry about that, and if you're still unable to run the script please comment!
