### ISSUE TITLE
Sharpness getting bug

### ISSUE THREAD

**Issue by jianchaoci** [GaTech-RL2/nvf_cvpr24#2]
I am on the step to get image, but I get a problem when runing the 'sharpness()'. And the error is attached below. I check the format of image, which is numpy arrary, but still getting the below problem. I noticed you once to read the image from the path, which enables the images in the format of cv2. I also tried the convert image to the format of cv2, but still get the problem. Can you help to check?

cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'

**Comment by JesseDill** [comment]
Can you show the entire stack trace? Also what blender scene are you generating images for
