### ISSUE TITLE
bpy==3.6.0 installation issue: Python version mismatch

### ISSUE THREAD

**Issue by spring520** [GaTech-RL2/nvf_cvpr24#4]
I encountered an issue while trying to install the required dependencies from requirements.txt. The file specifies bpy==3.6.0, but when attempting to install it via pip, I received an error indicating a Python version mismatch （shown below）. This error seems inconsistent with the Python version specified in the README file.

```bash
$ pip3 install bpy==3.6.0
ERROR: Ignored the following versions that require a different python version: 2.82.1 Requires-Python >=3.7, <3.8
ERROR: Could not find a version that satisfies the requirement bpy==3.6.0 (from versions: 3.4.0)
ERROR: No matching distribution found for bpy==3.6.0
```

Could anyone please clarify the specific installation steps or provide guidance on which Python version is compatible with bpy==3.6.0? Are there any additional steps or dependencies needed to successfully install bpy?

**Comment by xsj01** [comment]
Which OS and Blender version are you using? (You can check your Blender version by running `blender -v`). 
Could you try modifying `bpy==3.6.0` to just `bpy` in the` nvf/requirements` file?
