### ISSUE TITLE
About training bug.

### ISSUE THREAD

**Issue by EdenGabriel** [GaTech-RL2/nvf_cvpr24#5]
**Describe the bug**
hi, thanks for your interesting work. 
When i run the `python eval.py --scene hotdog --method nvf`, these has some error:

>
Start Training NeRF

Start Planning
Entropy Type: <class 'nvf.uncertainty.entropy_renderers.VisibilityEntropyRenderer'>
nvf_cvpr24/nerfstudio/fields/nerfacto_field.py", line 252, in get_density
    h = self.mlp_base(positions_flat).view(*ray_samples.frustums.shape, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [0, -1] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by JesseDill** [comment]
Hi there, sorry for the late reply. How did you setup your environment? I am able to run the command without issues on my machine.
