### ISSUE TITLE
question about aabb 

### ISSUE THREAD

**Issue by spring520** [GaTech-RL2/nvf_cvpr24#6]
I’m trying to visualize various AABBs in the code. I assume that object_aabb refers to a bounding box containing the target, while camera_aabb corresponds to a bounding box representing the camera's movable position. However, after directly loading the Hubble scene and adding two bounding boxes at the corresponding positions, I noticed that neither AABB seems to fully enclose the entire target. I’d like to ask if there are some coefficients involved here.

The visualization result is attached below.

Also, could you explain what the other AABBs in the code correspond to, such as the SceneBox(aabb=tensor([[-2., -2., -2.], [2., 2., 2.]])) used when initializing the NerfactorField and the array([[-5.53347384, -6.21497733, -6.34323449], [5.53346429, 10.51196569, 6.01754179]]) obtained from env.scene.get_aabb()?
![截屏2024-10-23 20 38 08](https://github.com/user-attachments/assets/d795ec92-eff9-4676-a69e-2b0b8381da4c)

**Comment by xsj01** [comment]
For the Hubble scene, we [rescaled it by a factor of 1/6](https://github.com/GaTech-RL2/nvf_cvpr24/blob/35e25066220f3108fe7072e149c698bdac773113/eval.py#L132), so it should be fully enclosed within the cfg.object_aabb. It seems the figure you showed is directly from the original mesh without rescaling.

`object_aabb ` serves as a coarse AABB used for NerfactorField, it is slightly larger than the object. The AABB obtained from `env.scene.get_aabb()` provides a more precise bounding box, directly derived from the mesh file.

And yes, `camera_aabb ` represents the bounding box that defines the camera's moveable positions.
